# ######################################################  #
#                    GENERAL SETTINGS                     #
# ######################################################  #
# Here you can manage the general settings for the core plugin.
language: english

# ######################################################  #
#                     LOGGING SYSTEM                      #
# ######################################################  #
# The Debug Logging system for the core plugin
# You can enable or disable the debug logging system
# and set the debug level.
logging:
  debug:
    enable: false
    level: 3

# ######################################################  #
#                       IO SYSTEM                         #
# ######################################################  #
# Here are the settings for the IO system.
# The Database and the Redis server.
redis:
  enable: false
  host: 'localhost'
  port: 6379
  password: ""
  database: 0

cross-server:
  enable: false
  sync-type: 'redis'
  server-name: 'default'

storage:
  # possible values:
  # - sqlite -> using SQLite (recommended for most users) (single server setup)
  # - mysql -> for a MySQL database
  # - mariadb -> for a MariaDB database (recommended over MySQL)
  type: sqlite
  host: 127.0.0.1
  port: 3306
  database: databaseName
  username: username
  password: YourSecretPassword
  advanced:
    # Don't change any values here if you don't know what you're doing.
    connection-timeout: 60000
    idle-timeout: 600000
    keep-alive-time: 0
    max-life-time: 1800000
    minimum-idle: 10
    # The maximum pool size of the connection pool for the database.
    # Bigger pool size = more performance, but more RAM/CPU usage.
    # If you installed more than 3 plugins from me, you should increase this value.
    # For example: 3 plugins -> 15, 4 plugins -> 20, 5 plugins -> 25
    # Default value is 10.
    maximum-pool-size: 10
    leak-detection-threshold: 0
    connection-test-query: "SELECT 1"
    character-encoding: "utf8"

damage-indicator:
  enable: false
  conditions: []
  fraction-digits: 0
  life-time-ticks: 15
  format:
    normal: <red>#damage#
    crit: <rainbow>#damage#
  scale:
    x: 2.0
    y: 2.0
    z: 2.0
  offset:
    x: 0.0
    y: 1.5
    z: 0.0
  velocity:
    in-x:
      min: 0.1
      max: 0.1
    in-y:
      min: 0.3
      max: 0.3
    in-z:
      min: 0.1
      max: 0.1
  numbers:
    normal:
      '0': '0'
      '1': '1'
      '2': '2'
      '3': '3'
      '4': '4'
      '5': '5'
      '6': '6'
      '7': '7'
      '8': '8'
      '9': '9'
    crit:
      '0': '0'
      '1': '1'
      '2': '2'
      '3': '3'
      '4': '4'
      '5': '5'
      '6': '6'
      '7': '7'
      '8': '8'
      '9': '9'